# This file stores configurations for your Shopify app.

scopes = "write_products, read_orders, read_customers, write_script_tags, read_customers, read_discounts, write_discounts, read_price_rules, write_price_rules, read_products, read_shipping"
